---
title: "Change the title to one of your choice"
author: "Toan Pham"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, fig.height = 4, fig.width = 6 )
```


```{r}
library(tidyverse)
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr) 
library(rlist)
```


```{r, CACHE = TRUE}
# read in data 
Colleges1 <- read.csv("https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Scorecard-Elements.csv")
Colleges2 <- read.csv("https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Treasury-Elements.csv")
Colleges3 <- read.csv("https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-All-Data-Elements.csv")
# dimensions should be:
# Colleges1 7112 by 190
# Colleges2 7112 by 92
# Colleges3 7112 by 1978
#check that this is the case
```

Type introductory paragraph. 
 

```{r}
#First figure (table or graph)
Project2 <- Colleges3 %>% 
  select(STABBR,INSTNM,SAT_AVG, contains("PCIP"),contains("DEBT"),MN_EARN_WNE_P10,MD_EARN_WNE_P10,  contains("MN_WNE_INC"),COUNT_WNE_P6,MD_EARN_WNE_P6,TUITIONFEE_IN,MN_EARN_WNE_MALE0_P10,MN_EARN_WNE_MALE1_P10,MN_EARN_WNE_MALE0_P6,MN_EARN_WNE_MALE1_P6)
TuitionData1 <- Project2 %>% 
  select(STABBR,TUITIONFEE_IN,MD_EARN_WNE_P6) %>%
  mutate_at(c("TUITIONFEE_IN","MD_EARN_WNE_P6") , as.character) %>%
  mutate_at(c("TUITIONFEE_IN","MD_EARN_WNE_P6") , as.numeric)
ggplot(data = TuitionData1) +
  geom_point(mapping = aes(x = log2(TUITIONFEE_IN), y = log2(MD_EARN_WNE_P6)),shape = 21,color = "black", size = 1, stroke = 1, fill = "white") +
  geom_smooth(mapping = aes(x = log2(TUITIONFEE_IN), y = log2(MD_EARN_WNE_P6)), size = 2, color = "blue") +
  theme_bw() +
  xlab("Tuition fee") +
  ylab("Earnings after 6 years")
```


one or two paragraph discussion of first figure


```{r}
#Second figure (figure or graph)
TuitionData2 <- Project2 %>% 
  select(STABBR,TUITIONFEE_IN,MD_EARN_WNE_P6,MD_EARN_WNE_P10) %>%
  mutate_at(c("TUITIONFEE_IN","MD_EARN_WNE_P6","MD_EARN_WNE_P10") , as.character) %>%
  mutate_at(c("TUITIONFEE_IN","MD_EARN_WNE_P6","MD_EARN_WNE_P10") , as.numeric) %>%
  group_by(STABBR) %>%
  summarize(medianFee = median(TUITIONFEE_IN,na.rm = TRUE),
            medianEarnafter6 = median(MD_EARN_WNE_P6, na.rm = TRUE),
            medianEarnafter10 = median(MD_EARN_WNE_P10, na.rm = TRUE)) %>%
  pivot_longer(cols = c(medianEarnafter6,medianEarnafter10), 
                                      names_to = "year", values_to="earnings") %>%
  filter(STABBR %in% c("CT","DC","IA", "MA","NE","NH","PA","RI","TN","VT"))
ggplot(data = TuitionData2) +
  geom_bar(mapping = aes(x =STABBR , y = earnings), stat = "identity",show.legend = FALSE) +
  facet_wrap(~ year) +
  coord_cartesian(ylim=c(25000,48000)) +
  theme_bw() +
  ylab("Average earnings after X years") +
  xlab("States") +
  labs(title = "Top 10 states with highest earnings after 6 and 10 years")

```

one or two paragraph discussion of second figure


```{r}
#Third figure (table or graph)
GenderData <- Project2 %>% 
  select(MN_EARN_WNE_MALE0_P10,MN_EARN_WNE_MALE1_P10) %>%
  mutate_at(c("MN_EARN_WNE_MALE0_P10","MN_EARN_WNE_MALE1_P10") , as.character) %>%
  mutate_at(c("MN_EARN_WNE_MALE0_P10","MN_EARN_WNE_MALE1_P10") , as.numeric) %>%
  rename(
    female = MN_EARN_WNE_MALE0_P10,
    male = MN_EARN_WNE_MALE1_P10
    ) %>%
  pivot_longer(cols = c(female,male), 
                                      names_to = "gender", values_to="earnings") %>%
  group_by(gender) %>%
  summarize(medianEarnings = median(earnings,na.rm = TRUE))
ggplot(data = GenderData) +
  geom_bar(mapping = aes(x = gender, y = medianEarnings), stat = "identity") + 
  theme_bw() +
  ylab("Median Earnings after 10 years") +
  xlab("Gender");
  
```

one or two paragraph discussion of third figure



```{r}
#Fourth figure (table or graph) - optional
DebtData <- Project2 %>% 
  select(GRAD_DEBT_MDN,MD_EARN_WNE_P10,LO_INC_DEBT_MDN,MD_INC_DEBT_MDN,HI_INC_DEBT_MDN)

```

one or two paragraph discussion of fourth figure



```{r}
#Fifth figure (table or graph) - optional
```

one or two paragraph discussion of fifth figure


## Appendix 

```{r}
#Additional figure(s) if desired
```